# Site settings
title: "Python"
description: "welcome to python world"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "mk,sr"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: hnbloggithub
